### ISSUE TITLE
Update freecad to v1.0.0

### ISSUE THREAD

**Issue by luzpaz** [spack/packages.spack.io#29]
Sorry if this is not the correct place to make this request. 

https://github.com/spack/packages.spack.io/blob/8b6fa8c23bdaa4be7929e7a3571f7f8f8a2a33f3/data/packages/freecad.json#L94

This is an outdated version. Current stable is 1.0.0 and is a historic milestone release for the project: https://blog.freecad.org/2024/11/19/freecad-version-1-0-released/

**Comment by alalazo** [comment]
@luzpaz Please submit a PR to https://github.com/spack/spack to update `freecad`. The JSON file here is created automatically on a daily base, based on metadata from the repo I linked.
